name: Inputs file
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      variable-passing:
        description: "This is input variable"
        default: "Kavya"
        type: string
        required: true
  jobs:
    calling-variable:
      runs-on: uuntu-latest
      steps: 
        - name: "printing the variable"
          run: echo "Variable is ${{ inputs.variable-passing }}"
