name : Matrix Learning
on:
  workflow_dispatch:
  push:

jobs:
  Matrix-learning-deploy:
    name: "Deploy on ${{ matrix.environment }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["dev", "UAT", "prod","QA"]
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
        
      - name: "Deploy ${{ matrix.environment }} step"
        run: echo "Deploying ${{ matrix.environment }}"
   