name: Variables-workflow
on: push
jobs:
  variable-job-running:
    runs-on: ubuntu-latest
    steps:
      - name: my-variable-print
        run: echo "This my ID ${{ vars.ID }}"
  variable-job-running-sec:
    need: variable-job-running
    runs-on: ubuntu-latest
    steps:
      - name: my-secrets-print
        run: echo "This is my secrets id ${{ secrets.my_id }}"  
        